### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by peterhj** [rejuvyesh/gym-dmcontrol#2]
A solid gym wrapper for dm_control is quite useful. However I noticed there is no open source license attached to this repository yet. A standard open source license would be an easy assurance for potential users of this repo, myself included :) dm_control itself is Apache 2.0-licensed so that might be a good candidate.

**Comment by rejuvyesh** [comment]
Hopefully fixes things? Didn't think it was a big enough contribution to be necessary.

**Comment by peterhj** [comment]
Thanks! I guess it is not a "big" gesture but having an explicit license is definitely meaningful.
